// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: assistant.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAssistant = `-- name: CreateAssistant :one
INSERT INTO assistant(assistant_id)
VALUES ($1)
returning assistant_id
`

func (q *Queries) CreateAssistant(ctx context.Context, assistantID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAssistant, assistantID)
	var assistant_id uuid.UUID
	err := row.Scan(&assistant_id)
	return assistant_id, err
}
