// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: educator.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createEducator = `-- name: CreateEducator :one
INSERT INTO educator(educator_id, educator_type)
VALUES ($1, $2)
RETURNING educator_id, educator_type
`

type CreateEducatorParams struct {
	EducatorID   uuid.UUID
	EducatorType string
}

func (q *Queries) CreateEducator(ctx context.Context, arg CreateEducatorParams) (Educator, error) {
	row := q.db.QueryRow(ctx, createEducator, arg.EducatorID, arg.EducatorType)
	var i Educator
	err := row.Scan(&i.EducatorID, &i.EducatorType)
	return i, err
}
