// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Assistant struct {
	AssistantID uuid.UUID
}

type Center struct {
	CenterID  uuid.UUID
	OwnerName pgtype.Text
	LogoUrl   pgtype.Text
	Location  pgtype.Text
}

type Educator struct {
	EducatorID   uuid.UUID
	EducatorType string
}

type Name struct {
	UserID     uuid.UUID
	FirstName  string
	MiddleName string
	LastName   string
}

type Outbox struct {
	ID            uuid.UUID
	EventType     string
	AggregateType string
	AggregateID   string
	Payload       []byte
	CreatedAt     time.Time
	PublishedAt   pgtype.Timestamptz
	Published     bool
}

type PhoneNumber struct {
	PhoneNumber string
	UserID      pgtype.UUID
}

type RevokedToken struct {
	Jti       uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Student struct {
	StudentID   uuid.UUID
	ParentPhone string
}

type Teacher struct {
	TeacherID uuid.UUID
}

type User struct {
	UserID       uuid.UUID
	PasswordHash string
	IsActive     pgtype.Bool
	UserType     string
}
