// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: student.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO student(student_id, parent_phone)
VALUES($1, $2)
RETURNING student_id, parent_phone
`

type CreateStudentParams struct {
	StudentID   uuid.UUID
	ParentPhone string
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.StudentID, arg.ParentPhone)
	var i Student
	err := row.Scan(&i.StudentID, &i.ParentPhone)
	return i, err
}
