// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: teacher.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTeacher = `-- name: CreateTeacher :one
INSERT INTO teacher(teacher_id)
VALUES ($1)
RETURNING teacher_id
`

func (q *Queries) CreateTeacher(ctx context.Context, teacherID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTeacher, teacherID)
	var teacher_id uuid.UUID
	err := row.Scan(&teacher_id)
	return teacher_id, err
}
